### ISSUE TITLE
Index pages for categories and tags

### ISSUE THREAD

**Issue by sbanwart** [carlos-algms/hexo-theme-materialize#6]
I am trying to setup a new blog using this theme, but I'm having trouble generating the index pages for the categories and tags. I've configured my site as follows:

```yaml
tag_dir: blog/tags
archive_dir: blog
category_dir: blog/categories
```

When I run `hexo generate`, the categories and tags are being generated under `/blog/categories/categoryname`, but there isn't an index page listing all of the categories. Same thing for tags.

Is this by design, or is there some other configuration parameter I've missed?

Thanks.
